"""empty message

Revision ID: 46a436be4d0a
Revises: abd9e7338b1f
Create Date: 2025-01-28 11:07:43.563309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46a436be4d0a'
down_revision = 'abd9e7338b1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userData',
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    )
    # with op.batch_alter_table('userdata', schema=None) as batch_op:
    #     batch_op.drop_index('email')

    # op.drop_table('userdata')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('userdata',
    # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    # sa.Column('passwd', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    # sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_unicode_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='MyISAM'
    # )
    # with op.batch_alter_table('userdata', schema=None) as batch_op:
    #     batch_op.create_index('email', ['email'], unique=True)

    op.drop_column('userData', 'date_joined')
    # ### end Alembic commands ###
